export const FETCH_USER_STATE_SUCCESS = "FETCH_USER_STATE_SUCCESS";
export const FETCH_USER_STATE_START = "FETCH_USER_STATE_START";
export const FETCH_USER_STATE_FAILURE = "FETCH_USER_STATE_FAILURE";
export const FETCH_USER_STATE_AUTH = "FETCH_USER_STATE_AUTH";
export const FETCH_USER_COURSE_ENROLL = "FETCH_USER_COURSE_ENROLL";
export const FETCH_USER_STATE_CLEAR = "FETCH_USER_STATE_CLEAR";