export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECT_ABOUT_SUCCESS = "FETCH_PROJECT_ABOUT_SUCCESS";
export const FETCH_PROJECT_ABOUT_LIST_SUCCESS =
  "FETCH_PROJECT_ABOUT_LIST_SUCCESS";
